### ISSUE TITLE
 dont working

### ISSUE THREAD

**Issue by LucasXDR** [GabCoder/ReShadeInjector#9]
seems dont work for now  24/07/2017

**Comment by Garry050** [comment]
what? i'm working now.
of cource, i can join official valve servers.

**Comment by LucasXDR** [comment]
how?? I put the injector and the d3d9. In the game folder, and when I go to open the game with the injector it immediately closes, and if I insist the steam gives me an access message denied to the game.   o.O

**Comment by Garry050** [comment]
How???????????? i don't know
start RSI.exe and start csgo that's only man

**Comment by LucasXDR** [comment]
Okay.. Can any program interfere with the injector? Maybe riva tuner.. shadowplay.. anything? I will try to disable it later

**Comment by GabCoder** [comment]
You have to start the injector first and only then the game, so you do?

**Comment by GabCoder** [comment]
Release version must work anywhere, idk what's your problem.
If at the start of the injector does not climb such a window, then the problem is clearly not in the injector
![rsi_2017-07-26_16-13-25](https://user-images.githubusercontent.com/18058477/28622542-83901590-721d-11e7-8b04-ff04e6864363.png)

**Comment by Garry050** [comment]
Reshade have conflict some overlay(like Millris Action capture recorder overlay)

**Comment by LucasXDR** [comment]
So... I checked the windows event viewer, and saw that it seems to be a csgo appcrash problem caused by ntdll.dll, I disable all my stuff and still dont working for me, btw the injector show the window, but when I start the game it sometimes says access denied on steam or the game simple dont show up.


Nome do aplicativo com falha: csgo.exe, versão: 0.0.0.0, carimbo de data/hora: 0x595ec8de
Nome do módulo com falha: **ntdll.dll**, versão: 10.0.15063.447, carimbo de data/hora: 0xd51d5c5e
Código de exceção: 0xc0000005
Deslocamento da falha: 0x0002be72
ID do processo com falha: 0x1bc0
Hora de início do aplicativo com falha: 0x01d306247ec3d10a
Caminho do aplicativo com falha: **C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe**
Caminho do módulo com falha: **C:\Windows\SYSTEM32\ntdll.dll**
ID do Relatório: 0d43ac77-56e0-466a-b201-d9bfe685f4d8
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha: 



Signature of the problem:
P1: csgo.exe
P2: 0.0.0.0
P3: 595ec8de
P4: ntdll.dll
P5: 10.0.15063.447
P6: d51d5c5e
P7: c0000005
P8: 0002be72
P9: 
P10:

**Comment by LucasXDR** [comment]
Nevermind, I solved the problem ^^
Theres a new option in windows 10 creators update, that causes conflict with the reshade, it "called disable full screen optimization" anyways, really thanks for the attention!
